# Generated by Django 3.2 on 2023-04-18 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defTruephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('defTruecountry', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('defTruepostcode', models.CharField(blank=True, max_length=20, null=True)),
                ('defTruetown_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('defTruestreet_addres1', models.CharField(blank=True, max_length=80, null=True)),
                ('defTruestreet_addres2', models.CharField(blank=True, max_length=80, null=True)),
                ('defTruecounty', models.CharField(blank=True, max_length=80, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
