# Generated by Django 3.2 on 2023-04-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='defTruecountry',
            new_name='default_country',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='defTruecounty',
            new_name='default_county',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='defTruephone_number',
            new_name='default_phone_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='defTruepostcode',
            new_name='default_postcode',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='defTruestreet_addres1',
            new_name='default_street_addres1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='defTruestreet_addres2',
            new_name='default_street_addres2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='defTruetown_or_city',
            new_name='default_town_or_city',
        ),
    ]
